### ISSUE TITLE
Failed to Setup

### ISSUE THREAD

**Issue by bubba925** [iMicknl/ha-nest-protect#234]
### The problem

After updating from 2023.4.5 to May or June release nest protect fails to setup. Attempted deleting and re-installing integration with no success. Using cookie method...

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.6.1

### Device / Model

Nest Protect Battery and Wired

### Home Assistant log

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect (documentation, issues)
First occurred: 10:20:02 AM (1 occurrences)
Last logged: 10:20:02 AM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by iMicknl** [comment]
Please update to the latest version of this integration (beta) https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b1. Most likely you did configure a custom repository via HACS, which is a fork of this integration.
