### ISSUE TITLE
AttributeError: 'list' object has no attribute 'object_key'

### ISSUE THREAD

**Issue by TomvHoof** [iMicknl/ha-nest-protect#383]
### The problem

After updating to 0.4.0b8 the following error occurs and keeps retrying every 5 minutes:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 209, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b8

### What version of Home Assistant Core has the issue?

2024.12.1

### Home Assistant log

<details><summary>Logs</summary>

```
2024-12-11 00:59:33.908 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 209, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-12-11 01:04:34.660 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 209, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-12-11 01:09:35.309 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 209, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>
