### ISSUE TITLE
 After updating to 0.4.0.b1 getting Authentication error: invalid_request even though it appears to be working fine

### ISSUE THREAD

**Issue by alexruffell** [iMicknl/ha-nest-protect#221]
### The problem

I updated to 0.4.0.b1 and while it appears to be working with cookie authentication (occupancy updates), I am getting this error in the logs:

```
2023-04-26 09:31:02.356 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-04-26 09:31:02.357 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-04-26 09:31:02.357 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
self.nest_session = NestResponse(**nest_response)
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
entry_data.client.nest_session = await entry_data.client.authenticate(auth)
File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
```

### What version of this integration (ha-nest-protect) has the issue?

0.4.0.b1

### What version of Home Assistant Core has the issue?

core-2023.4.6

### Device / Model

Nest Protect - AC - Topaz-2.7

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by AustinTiger** [comment]
I have the same issue, but I'm a new user.
ha-nest-protect v0.3.12
ha-core: v2023.04.1
device: Topaz-2.9

**Comment by iMicknl** [comment]
@AustinTiger your issue is not related. You need the prerelease if you are a new user. I will clarify the readme soon.
