### ISSUE TITLE
After HA update to 2023.5.0 , Nest-protect integration no longer works

### ISSUE THREAD

**Issue by Vinisz** [iMicknl/ha-nest-protect#224]
### The problem

Hi, after updating HA yesterday to 2023.5.0 and rebooting, the NEST-protect integration no longer works and gives below error:
Would be great if you can have a look to see if this can be fixed.

```
Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 3 mei 2023 om 23:44:12 (3 occurrences)
Last logged: 11:18:35

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### What version of this integration (ha-nest-protect) has the issue?

latest

### What version of Home Assistant Core has the issue?

2023.5.0

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Are you sure you updated to the latest version? I cannot reproduce your issue on the latest version.

**Comment by oppergod** [comment]
I'm encountering the same issue:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

**Comment by Vinisz** [comment]
Latest HA you mean or latest nest-protect plugin? Op 4 mei 2023 om 11:48 heeft Mick Vleeshouwer ***@***.***> het volgende geschreven:﻿
Are you sure you updated to the latest version? I cannot reproduce your issue on the latest version.

**Comment by iMicknl** [comment]
Can you both double check that you run the latest version of Nest Protect? (v0.3.12 OR v0.4.0b1)
See https://github.com/iMicknl/ha-nest-protect/releases.

Did you install any cookie method version perhaps? Probably you did switch to another fork.

**Comment by oppergod** [comment]
I found the issue, was using a fork from this repository (https://github.com/nicoinch/ha-nest-protect), which is showing this issue.

Sorry for the inconvenience.

**Comment by iMicknl** [comment]
@Vinisz do you use HACS? Click redownload and select v0.3.12 (old login method) or v0.4.0b1 (cookie method), depending on what you need.

**Comment by Vinisz** [comment]
Funny, when I do click on "repository" there (in HACS) , it brings me here: https://github.com/nicoinch/ha-nest-protect , so I guess it seems I do use a fork then ? not sure how that exactly is possible, how can I make sure I use yours from HACS ?

**Comment by iMicknl** [comment]
<img width="192" alt="image" src="https://user-images.githubusercontent.com/1424596/236178103-04e9353b-0624-4f68-8854-249cbdbc6f86.png">
Remove the custom repository here. You can remove the version from the fork and reinstall the Nest Protect directly from HACS.

**Comment by Vinisz** [comment]
Ok, that worked... Had to go for latest beta because otherwise I ran into this issue : https://github.com/iMicknl/ha-nest-protect/issues/105

The, I used these instructions: https://github.com/nicoinch/ha-nest-protect#retrieving-issue_token-and-cookies to get the token and cookies (I think you should update the 2 fiels for the beta to reflect what should go where and how to get it)

At the end, bit of crazy way to get it all but hey, it worked and It's not something we have to do daily.
Thanks for your quick responses and help... happy end-user ;-)

**Comment by iMicknl** [comment]
Yes, the beta (not coded by me) lacks clear instructions I have to say. That is also the reason why it is not merged in main yet, but only listed as a pre-release. 

There has been great work done by the community to add the cookie method, and now we just need to finish it a bit and add clear instructions.

**Comment by Vinisz** [comment]
Yeah well, that's just the finishing , that it technically works is already great indeed...

**Comment by tggman** [comment]
Maybe this was expected by those of you familiar with where authentication info is stored in HA, but for those of you wondering ...
 
I updated from the @nicoinch forked version to @iMicknl v0.4.0b1 version without having to reauthenticate. A couple months back I used the manual method (not HACS) to initially install and authenticate the @nicoinch integration. Today I replaced that version by manually deleting the ```custom_components/nest_protect``` folder and replacing it with the @iMicknl version.  Since I deleted the entire ```nest_protect``` folder I expected I would need to re-enter the ```issue_token``` and ```cookie``` values but that was not necessary!

Just out of curiosity, and for my future reference, where is this authentication info stored within Home Assistant?
