### ISSUE TITLE
error initializing the integration after update to 2023.5.1

### ISSUE THREAD

**Issue by xkahn** [iMicknl/ha-nest-protect#227]
### The problem

After updating to 2023.5.1

```Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

 2023.5.1

### Device / Model

nest protect battery

### Diagnostics information

Device showed up in error

### Home Assistant log

<details><summary>Logs</summary>
```
Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

</details>

### Additional information

After update the integration will not start

**Comment by MiSpri1974** [comment]
Same here

**Comment by iMicknl** [comment]
Duplicate of #224. You need to update to the latest version.
